# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VOqEqYecoIu_nsIId9xl4t-pUtwv7H_q
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/customer_shopping_behavior.csv")

df.head()

df.info()

df.describe()

df[df["Review Rating"].isnull()].head()

df["Review Rating"] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

df.isnull().sum()

df.columns =df.columns.str.lower()

df.columns=df.columns.str.replace(" ","_")

df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

## age group
labels = ['Young Adult','Adult','Middled_aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels = labels)

# purchase_frequency
frequency_mapping = {
    'Fortnightly' :14,
    'Weekly' : 7,
    'Monthly' : 30,
    'Quaterly' : 90,
    'Bi-weekly':14,
    'Annually' : 365,
    'Every 3 Months':90
}
df['purchase_frequency_days'] =df['frequency_of_purchases'].map(frequency_mapping)

df = df.drop('promo_code_used',axis=1)

df.head()